export const NAV_LINKS = [
  { label: 'Home', href: '#' },
  { label: 'About', href: '#about' },
  { label: 'Projects', href: '#projects' },
  { label: 'Stack', href: '#stack' },
  { label: 'Writing', href: '#writing' },
  { label: 'Contact', href: '#contact' },
] as const

export const STACK_ITEMS = [
  { name: 'React', role: 'UI / Frontend', icon: 'SiReact' },
  { name: 'TypeScript', role: 'Language', icon: 'SiTypescript' },
  { name: 'Next.js', role: 'Framework', icon: 'SiNextdotjs' },
  { name: 'React Native', role: 'Mobile', icon: 'SiReact' },
  { name: 'Tailwind', role: 'Styling', icon: 'SiTailwindcss' },
  { name: 'Node.js', role: 'Backend', icon: 'SiNodedotjs' },
  { name: 'PostgreSQL', role: 'Database', icon: 'SiPostgresql' },
  { name: 'Python', role: 'Scripting', icon: 'SiPython' },
  { name: 'Git', role: 'Version ctrl', icon: 'SiGit' },
  { name: 'Docker', role: 'DevOps', icon: 'SiDocker' },
  { name: 'Figma', role: 'Design', icon: 'SiFigma' },
  { name: 'Vercel', role: 'Deployment', icon: 'SiVercel' },
] as const

export const PROJECTS = [
  {
    num: '01',
    type: 'Concept',
    name: 'Discrep',
    desc: 'A framework and tool for closing the gap between who you think you are and how you actually behave. Not by telling you who to be, but by showing you the pattern.',
    longDesc: 'Most people don\'t lack self-awareness. They lack an honest mirror. Self-Coherence is a framework built around a simple but uncomfortable observation: the gap between our stated values and our actual behavior is one of the most consequential and least examined parts of being human.\n\nThe framework organizes self-assessment around five strictly internal dimensions — Integrity, Autonomy, Awareness, Accountability, and Courage — grounded in decades of psychological research including Higgins, Rogers, Deci & Ryan, and Brené Brown.\n\nThe idea came from personal experience, not academic research. Currently in early stage: a position paper exists, real conversations are being had, and the shape of the product is forming.',
    images: [],
    stack: [],
    link: null,
    linkLabel: null,
    wip: false,
    brainstorm: true,
  },
  {
    num: '02',
    type: 'Side project',
    name: 'oneMore',
    desc: 'A cigarette tracking app that helps smokers build awareness of their habits — not by pressuring them to quit, but by turning an unconscious habit into a conscious choice.',
    longDesc: 'oneMore is a personal cigarette tracking app designed to help smokers build awareness of their habits and take meaningful steps toward smoking less. By logging each cigarette in real time, users gain a clear picture of how much they smoke, when they smoke, and what triggers their cravings.\n\nThe app focuses on simplicity and honesty — rather than pressuring users to quit cold turkey, oneMore meets them where they are, encouraging gradual reduction one cigarette at a time. Every log is a moment of mindfulness, turning an unconscious habit into a conscious choice.\n\nWith insights into daily and weekly patterns, oneMore empowers users to set their own pace, celebrate small wins, and stay motivated on their journey toward a healthier life.',
    images: [
      '/projects/one-more/one-more1.png',
      '/projects/one-more/one-more2.png',
      '/projects/one-more/one-more3.png',
      '/projects/one-more/one-more4.png',
      '/projects/one-more/one-more5.png',
      '/projects/one-more/one-more6.png',
    ],
    stack: ['TypeScript', 'React Native', 'Expo'],
    link: null,
    linkLabel: null,
    wip: false,
    brainstorm: false,
  },
  {
    num: '03',
    type: 'Client work',
    name: 'Marineria.it',
    desc: 'A cross-platform mobile app bringing a maritime recruitment platform to iOS and Android — real-time job listings, crew profiles, and recruiter tools.',
    longDesc: 'A cross-platform mobile app built with React Native, Expo, and TypeScript that brings the Marineria.it maritime recruitment platform to iOS and Android. All data is fetched in real time via REST API integration, keeping job listings, profiles, and applications in sync with the existing backend. The app is fully usable without an account, lowering the barrier for first-time users.\n\nGuests can browse and filter all live job offers. Crew users can create a profile, apply for positions, and see clear feedback when they don\'t meet requirements. Recruiters can post and manage offers, search candidates by skills or location, view detailed crew profiles with certifications and experience, and contact applicants directly.\n\nPush notifications are delivered to crew when a new matching job is published, and to recruiters when a candidate applies — keeping both sides of the marketplace engaged in real time. The app is fully localised in Italian and English, with an in-app language toggle available at any time from settings.\n\nSupports both one-time email code (OTP) and password login. Users can also register directly as crew or recruiter from the login screen.',
    images: [
      '/projects/marineria/marineria1.png',
      '/projects/marineria/marineria2.png',
      '/projects/marineria/marineria3.png',
      '/projects/marineria/marineria4.png',
      '/projects/marineria/marineria5.png',
      '/projects/marineria/marineria6.png',
      '/projects/marineria/marineria7.png',
      '/projects/marineria/marineria8.png',
    ],
    stack: ['TypeScript', 'React Native', 'Expo'],
    link: 'https://marineria.it',
    linkLabel: 'Visit site',
    wip: false,
    brainstorm: false,
  },
  {
    num: '04',
    type: 'Client work',
    name: 'Moviemiento',
    desc: 'A fully custom, pixel-perfect website for a Berlin-based cultural non-profit — traveling cinema, bicycle screenings, and international film projects.',
    longDesc: 'Developed a fully custom, pixel-perfect website for Moviemiento, a Berlin-based cultural non-profit known for its traveling cinema, bicycle cinema screenings, and international film and education projects.\n\nBuilt on WordPress with a fully custom PHP theme — no page builders, no pre-made templates. The design was translated from scratch into hand-written HTML and CSS, achieving a precise match to the original visual concept across all screen sizes.\n\nThe site is fully responsive and supports both German and English, with clean navigation, a news archive spanning multiple pages, project listings, and dynamic image content throughout.',
    images: [
      '/projects/moviemiento/moviemiento3.png',
      '/projects/moviemiento/moviemiento4.png',
      '/projects/moviemiento/moviemiento5.png',
      '/projects/moviemiento/moviemiento6.png',
    ],
    stack: ['PHP', 'WordPress', 'HTML', 'CSS'],
    link: 'https://www.moviemiento.org',
    linkLabel: 'Visit site',
    wip: false,
    brainstorm: false,
  },
] as const

export const WRITING_TAGS = ['Politics', 'Philosophy', 'Tech & Society', 'General'] as const

export const CONTACT_ITEMS = [
  { type: 'Email', value: 'n_nassif@icloud.com', action: 'Write ↗', href: 'mailto:n_nassif@icloud.com' },
  { type: 'GitHub', value: '@nassif', action: 'View ↗', href: 'https://github.com' },
  { type: 'LinkedIn', value: 'Nassif Nassif', action: 'Connect ↗', href: 'https://linkedin.com' },
  { type: 'Resume', value: 'PDF · 2025', action: 'Download ↗', href: '/resume.pdf' },
] as const
